root: true
parser: '@typescript-eslint/parser'
parserOptions:
    project: './tsconfig.json'
    sourceType: module
env:
    node: true
    es6: true
    jest: true
    mocha: true
plugins:
    - 'import'
extends:
    - 'eslint:recommended'
    - 'plugin:@typescript-eslint/recommended'
    - 'plugin:@typescript-eslint/recommended-requiring-type-checking'
    - 'plugin:prettier/recommended'
    - 'plugin:import/errors'
    - 'plugin:import/warnings'
    - 'plugin:import/typescript'
ignorePatterns:
    - 'build/*'
    - 'tests/**/*.js'
    - 'examples/*'
    - 'bin/*'
    - '.yarn/*'
    - 'scripts/*'
    - 'jest.config.js'
rules:
    'no-console': 'warn'
    'no-duplicate-imports': 'error'
    'no-return-await': 'error'
    'no-unneeded-ternary': 'error'
    'no-unused-vars': [ 'off' ]
    'prefer-object-spread': 'error'
    'require-await': 'off'
    '@typescript-eslint/ban-ts-comment': 'warn'
    '@typescript-eslint/restrict-template-expressions': 'warn'
    '@typescript-eslint/unbound-method': 'warn'
    '@typescript-eslint/no-unsafe-argument': 'warn'
    '@typescript-eslint/explicit-function-return-type': 'error'
    '@typescript-eslint/no-unsafe-assignment': 'warn'
    '@typescript-eslint/no-unsafe-member-access': 'warn'
