name: Continuous integration
on: 
  push:
  pull_request:
    branches: [master]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x]
        cucumber-version: [9.x, 10.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn add -P @cucumber/cucumber@${{ matrix.cucumber-version }}

      - name: Eslint
        run: yarn lint

      - name: Prettier
        run: yarn check-fmt

      - name: Tests
        run: yarn test-cli

      - name: Coverage
        run: yarn test-cover

      - name: Coveralls Parallel
        env:
          COVERALLS_FLAG_NAME: run-${{ matrix.node-version }}-${{ matrix.cucumber-version }}
        uses: coverallsapp/github-action@2.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true

  coverall:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@v2.3.0
        with:
            github-token: ${{ secrets.github_token }}
            parallel-finished: true
