name: Continuous integration
on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        node-version: [20.x, 22.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Eslint
        run: pnpm run lint

      - name: Prettier
        run: pnpm run check-fmt

      - name: Tests
        run: pnpm run test-func

      - name: Clear Jest cache
        run: pnpm jest --clearCache

      - name: Coverage
        run: pnpm run test-cover
        continue-on-error: true

      - name: Coveralls Parallel
        env:
          COVERALLS_FLAG_NAME: run-${{ matrix.node-version }}
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true

  coverall:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true
